{% set version = "0.0.1" %}

package:
  name: simple_ts_forecast
  version: {{ version }}

source:
  git_url: https://github.com/svkov/simple_ts_forecast.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/svkov/simple_ts_forecast
  license: MIT
  summary: 'A simle library for time series forecasting'
  description: |
    A simle library for time series forecasting
  dev_url: https://github.com/svkov/simple_ts_forecast
  doc_url: https://github.com/svkov/simple_ts_forecast