{% set version = "0.0.1" %}

package:
  name: simple_ts_forecast
  version: {{ version }}

source:
  git_url: https://github.com/svkov/simple_ts_forecast

build:
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - imagesize

about:
  home: https://github.com/svkov/simple_ts_forecast
  license: MIT
  summary: 'A simle library for time series forecasting'
  description: |
    A simle library for time series forecasting
  dev_url: https://github.com/svkov/simple_ts_forecast
  doc_url: https://github.com/svkov/simple_ts_forecast